# Generated by Django 4.2.11 on 2026-04-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_master_organization_mastershift_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='color',
            field=models.CharField(default='#3C50E0', help_text='Hex color code for calendar appointments', max_length=7),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
