# Generated by Django 4.2.11 on 2026-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_color_alter_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
