# Generated by Django 4.2.11 on 2026-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_master_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='full_name',
        ),
        migrations.AddField(
            model_name='master',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='master',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
