# Generated by Django 4.2.11 on 2026-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_master_full_name_master_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastershift',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
