# Generated by Django 4.2.11 on 2026-04-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_mastershift_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio in Markdown format'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/photos/'),
        ),
    ]
