# Generated by Django 4.2.11 on 2026-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_add_bio_to_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastershift',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text='Actual time when the master began the shift.', null=True),
        ),
    ]
