# Generated by Django 4.2.11 on 2026-04-23 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_organization_bot_username_organization_tma_name'),
        ('masters', '0008_mastershift_actual_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='master',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastershift',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastershift',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='masters.master'),
        ),
        migrations.AlterField(
            model_name='mastershift',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_shifts', to='organization.organization'),
        ),
    ]
