# Generated by Django 4.2.11 on 2026-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_remove_master_first_name_remove_master_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastershift',
            name='opened_by_admin',
            field=models.BooleanField(default=False, help_text='True if the shift was manually opened by an administrator'),
        ),
    ]
