# Generated by Django 4.2.11 on 2026-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_mastershift_opened_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
