# Generated by Django 4.2.11 on 2026-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_confirmation',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('yes', 'Да, приду'), ('no', 'Нет, не приду')], default='pending', max_length=10),
        ),
    ]
