# Generated by Django 4.2.11 on 2026-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_client_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Причина отмены, если статус cancelled', null=True),
        ),
    ]
