# Generated by Django 4.2.11 on 2026-04-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('single', 'Обычная'), ('combo_master', 'Комбо (Основная)'), ('combo_sub', 'Комбо (Дочерняя)')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appointments.appointment'),
        ),
    ]
