# Generated by Django 4.2.11 on 2026-04-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_service_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
