# Generated by Django 4.2.11 on 2026-05-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_is_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='kaspi_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
