# Generated by Django 4.2.11 on 2026-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_is_paid_appointment_kaspi_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_phone_for_invoice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('no_payment_required', 'Предоплата не требуется'), ('pending_auto_payment', 'Ожидает авто-оплаты'), ('pending_manual_invoice', 'Ожидает выставления счета'), ('paid', 'Оплачено')], default='no_payment_required', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prepayment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
