# Generated by Django 4.2.11 on 2026-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_client_phone_for_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Файл PDF-квитанции или фото чека предоплаты', null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('no_payment_required', 'Предоплата не требуется'), ('pending_auto_payment', 'Ожидает авто-оплаты'), ('pending_manual_invoice', 'Ожидает выставления счета'), ('pending_receipt', 'Ожидает квитанцию'), ('review', 'На проверке админа'), ('paid', 'Оплачено')], default='no_payment_required', max_length=30),
        ),
    ]
