# Generated by Django 4.2.11 on 2026-04-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='services.service')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_combos', to='services.service')),
            ],
        ),
    ]
