# Generated by Django 4.2.11 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_combo_comboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_strategy',
            field=models.CharField(choices=[('equal_split', '50/50 (Мастер и Салон)'), ('master_only', 'Только Мастер'), ('owner_only', 'Только Салон')], default='owner_only', max_length=20),
        ),
    ]
