# Generated by Django 4.2.11 on 2026-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_discount_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
