# Generated by Django 4.2.11 on 2026-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboitem',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
