# Generated by Django 4.2.11 on 2026-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_comboitem_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_floating_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
