# Generated by Django 4.2.11 on 2026-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_is_floating_price_service_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_prepayment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='prepayment_type',
            field=models.CharField(choices=[('fixed', 'Фикс'), ('percent', 'Процент')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='prepayment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
