# Generated by Django 4.2.11 on 2026-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('fixed', 'Постоянный'), ('variable', 'Переменный')], default='variable', max_length=10, verbose_name='Тип расхода'),
        ),
    ]
