# Generated by Django 4.2.11 on 2026-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensecategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_type',
            field=models.CharField(choices=[('fixed', 'Постоянный'), ('variable', 'Переменный')], default='variable', max_length=10, verbose_name='Тип расхода'),
        ),
    ]
