# Generated by Django 4.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('message_ru', models.TextField(help_text='Поддерживается плейсхолдер {{user_name}}', verbose_name='Сообщение (RU)')),
                ('message_kz', models.TextField(help_text='Поддерживается плейсхолдер {{user_name}}', verbose_name='Сообщение (KZ)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Время отправки')),
                ('audience_type', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные (записи за последние 60 дней)'), ('inactive', 'Неактивные (без активности более 60 дней)')], default='all', max_length=20, verbose_name='Сегмент аудитории')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('in_progress', 'В процессе'), ('done', 'Завершена'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_success', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок отправки')),
                ('unsubscribed_count', models.PositiveIntegerField(default=0, verbose_name='Отписалось (403)')),
                ('last_processed_user_id', models.IntegerField(default=0, verbose_name='Последний обработанный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='organization.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
