--
-- PostgreSQL database dump
--

\restrict uV3cNUiEEwguLkF6r3veQAwYGE4YG17j9hJf4XNre6xTIBl0Na6mudR242XokLv

-- Dumped from database version 15.15
-- Dumped by pg_dump version 18.0

-- Started on 2026-04-23 10:20:33 +05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 16454)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16453)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16462)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16461)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16448)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16447)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 16932)
-- Name: billing_phones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.billing_phones (
    id uuid NOT NULL,
    phone character varying(20) NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.billing_phones OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 33442)
-- Name: bot_sync_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bot_sync_tokens (
    id bigint NOT NULL,
    bot_sync_uuid uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.bot_sync_tokens OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 33441)
-- Name: bot_sync_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bot_sync_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bot_sync_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16798)
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    city_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    iiko_city_id uuid
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16526)
-- Name: delivery_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery_addresses (
    id uuid NOT NULL,
    house character varying(50),
    flat character varying(50),
    entrance character varying(50),
    floor character varying(50),
    latitude numeric(10,7),
    longitude numeric(10,7),
    comment text,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    street_id uuid,
    user_id uuid NOT NULL,
    city_name character varying(100) NOT NULL,
    iiko_city_id uuid,
    iiko_street_id uuid,
    street_name character varying(255),
    city_id uuid,
    is_verified boolean NOT NULL
);


ALTER TABLE public.delivery_addresses OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 33415)
-- Name: discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discounts (
    id bigint NOT NULL,
    external_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    percent numeric(10,2) NOT NULL,
    mode character varying(50) NOT NULL,
    is_manual boolean NOT NULL,
    is_active boolean NOT NULL,
    is_deleted_in_iiko boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL
);


ALTER TABLE public.discounts OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 33414)
-- Name: discounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.discounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16588)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16587)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16440)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16439)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16386)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16385)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16851)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 16895)
-- Name: fast_menu_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fast_menu_groups (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    image character varying(100),
    CONSTRAINT fast_menu_groups_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.fast_menu_groups OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 16901)
-- Name: fast_menu_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fast_menu_items (
    id uuid NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    group_id uuid NOT NULL,
    product_id uuid NOT NULL
);


ALTER TABLE public.fast_menu_items OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 33400)
-- Name: iiko_request_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.iiko_request_logs (
    id bigint NOT NULL,
    payload jsonb NOT NULL,
    success boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id uuid NOT NULL
);


ALTER TABLE public.iiko_request_logs OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 33399)
-- Name: iiko_request_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.iiko_request_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iiko_request_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 33531)
-- Name: mailing_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mailing_tasks (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    message_ru text NOT NULL,
    message_kz text NOT NULL,
    audience_type character varying(32) NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    total_recipients integer NOT NULL,
    sent_ru integer NOT NULL,
    sent_kz integer NOT NULL,
    failed_count integer NOT NULL,
    unsubscribed_count integer NOT NULL,
    last_processed_user_id uuid,
    organization_id uuid NOT NULL,
    CONSTRAINT mailing_tasks_failed_count_check CHECK ((failed_count >= 0)),
    CONSTRAINT mailing_tasks_sent_kz_check CHECK ((sent_kz >= 0)),
    CONSTRAINT mailing_tasks_sent_ru_check CHECK ((sent_ru >= 0)),
    CONSTRAINT mailing_tasks_total_recipients_check CHECK ((total_recipients >= 0)),
    CONSTRAINT mailing_tasks_unsubscribed_count_check CHECK ((unsubscribed_count >= 0))
);


ALTER TABLE public.mailing_tasks OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 33530)
-- Name: mailing_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mailing_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mailing_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16628)
-- Name: menus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menus (
    menu_id uuid NOT NULL,
    menu_name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    source_type character varying(20) NOT NULL,
    metadata jsonb
);


ALTER TABLE public.menus OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16652)
-- Name: modifiers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modifiers (
    modifier_id uuid NOT NULL,
    modifier_name character varying(255) NOT NULL,
    min_amount integer NOT NULL,
    max_amount integer NOT NULL,
    modifier_code character varying(100),
    modifier_weight numeric(10,2),
    price numeric(10,2) NOT NULL,
    is_required boolean NOT NULL,
    updated_from_iiko timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id uuid,
    is_available boolean NOT NULL
);


ALTER TABLE public.modifiers OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16725)
-- Name: order_item_modifiers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_item_modifiers (
    id uuid NOT NULL,
    modifier_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modifier_id uuid NOT NULL,
    order_item_id uuid NOT NULL
);


ALTER TABLE public.order_item_modifiers OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16720)
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id uuid NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id uuid NOT NULL,
    product_id uuid NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16713)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    order_id uuid NOT NULL,
    iiko_order_id uuid,
    status character varying(50) NOT NULL,
    order_number character varying(100),
    total_amount numeric(10,2) NOT NULL,
    phone character varying(20) NOT NULL,
    comment text,
    latitude numeric(10,7),
    longitude numeric(10,7),
    sent_to_iiko_at timestamp with time zone,
    iiko_response jsonb,
    error_message text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    delivery_address_id uuid,
    org_id uuid NOT NULL,
    payment_type_id uuid,
    user_id uuid NOT NULL,
    terminal_id uuid,
    correlation_id uuid,
    iiko_delivery_number character varying(100),
    query_to_iiko jsonb,
    delivery_cost numeric(10,2) NOT NULL,
    retry_count smallint NOT NULL,
    CONSTRAINT orders_retry_count_check CHECK ((retry_count >= 0))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16400)
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations (
    org_id uuid NOT NULL,
    org_name character varying(255) NOT NULL,
    api_key character varying(255),
    city character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    iiko_organization_id character varying(255),
    address character varying(500),
    phone character varying(50),
    bot_token character varying(255),
    bot_username character varying(255),
    primary_color character varying(7),
    api_custom_params jsonb,
    yandex_maps_api_key character varying(255),
    webhook_link character varying(500)
);


ALTER TABLE public.organizations OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16407)
-- Name: payment_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_types (
    payment_id uuid NOT NULL,
    payment_name character varying(255) NOT NULL,
    payment_type character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    system_type character varying(50)
);


ALTER TABLE public.payment_types OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16633)
-- Name: product_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_categories (
    subgroup_id uuid NOT NULL,
    subgroup_name character varying(255) NOT NULL,
    order_index integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    menu_id uuid,
    outer_data jsonb,
    parent_id uuid,
    id uuid NOT NULL
);


ALTER TABLE public.product_categories OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16638)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    product_id uuid NOT NULL,
    product_name character varying(255) NOT NULL,
    product_code character varying(100),
    price numeric(10,2) NOT NULL,
    measure_unit character varying(50) NOT NULL,
    has_modifiers boolean NOT NULL,
    is_available boolean NOT NULL,
    description text,
    image_url character varying(500),
    order_index integer NOT NULL,
    updated_from_iiko timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    menu_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    category_id uuid,
    outer_data jsonb,
    parent_group character varying(255),
    type character varying(50),
    id uuid NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16494)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role_name character varying(50) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16493)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16645)
-- Name: stop_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stop_list (
    id uuid NOT NULL,
    product_name character varying(255) NOT NULL,
    balance numeric(10,2) NOT NULL,
    reason text,
    is_auto_added boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    product_id uuid NOT NULL,
    terminal_id uuid
);


ALTER TABLE public.stop_list OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16412)
-- Name: streets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.streets (
    street_id uuid NOT NULL,
    street_name character varying(255) NOT NULL,
    iiko_street_id uuid,
    city_id uuid,
    is_deleted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL
);


ALTER TABLE public.streets OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16393)
-- Name: terminals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.terminals (
    terminal_id uuid NOT NULL,
    terminal_group_name character varying(255),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    iiko_organization_id character varying(255),
    organization_id uuid,
    city_id uuid,
    stop_list_interval_min integer NOT NULL,
    delivery_zones_conditions jsonb,
    working_hours jsonb,
    is_delivery_calculation_apply boolean NOT NULL,
    instagram_link character varying(500)
);


ALTER TABLE public.terminals OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16503)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    telegram_id bigint,
    telegram_username character varying(255),
    phone character varying(20),
    iiko_user_id uuid,
    updated_at timestamp with time zone NOT NULL,
    org_id uuid,
    role_id bigint,
    created_at timestamp with time zone NOT NULL,
    language_code character varying(5) NOT NULL,
    is_bot_subscribed boolean,
    chat_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16515)
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16514)
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16862)
-- Name: users_terminals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_terminals (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    terminal_id uuid NOT NULL
);


ALTER TABLE public.users_terminals OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16861)
-- Name: users_terminals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_terminals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_terminals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16521)
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16520)
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3442 (class 2606 OID 16491)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3447 (class 2606 OID 16477)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3450 (class 2606 OID 16466)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3444 (class 2606 OID 16458)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3437 (class 2606 OID 16468)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3439 (class 2606 OID 16452)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3573 (class 2606 OID 16936)
-- Name: billing_phones billing_phones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_phones
    ADD CONSTRAINT billing_phones_pkey PRIMARY KEY (id);


--
-- TOC entry 3586 (class 2606 OID 33448)
-- Name: bot_sync_tokens bot_sync_tokens_bot_sync_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bot_sync_tokens
    ADD CONSTRAINT bot_sync_tokens_bot_sync_uuid_key UNIQUE (bot_sync_uuid);


--
-- TOC entry 3588 (class 2606 OID 33446)
-- Name: bot_sync_tokens bot_sync_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bot_sync_tokens
    ADD CONSTRAINT bot_sync_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3542 (class 2606 OID 16822)
-- Name: cities cities_organization_id_city_id_3dbfa51d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_organization_id_city_id_3dbfa51d_uniq UNIQUE (organization_id, city_id);


--
-- TOC entry 3544 (class 2606 OID 16802)
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (city_id);


--
-- TOC entry 3479 (class 2606 OID 16532)
-- Name: delivery_addresses delivery_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_addresses
    ADD CONSTRAINT delivery_addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3579 (class 2606 OID 33421)
-- Name: discounts discounts_external_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_external_id_key UNIQUE (external_id);


--
-- TOC entry 3582 (class 2606 OID 33419)
-- Name: discounts discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_pkey PRIMARY KEY (id);


--
-- TOC entry 3484 (class 2606 OID 16595)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3432 (class 2606 OID 16446)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3434 (class 2606 OID 16444)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3410 (class 2606 OID 16392)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3547 (class 2606 OID 16857)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3560 (class 2606 OID 16900)
-- Name: fast_menu_groups fast_menu_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_groups
    ADD CONSTRAINT fast_menu_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3566 (class 2606 OID 16913)
-- Name: fast_menu_items fast_menu_items_group_id_product_id_44b72eb3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_items
    ADD CONSTRAINT fast_menu_items_group_id_product_id_44b72eb3_uniq UNIQUE (group_id, product_id);


--
-- TOC entry 3568 (class 2606 OID 16905)
-- Name: fast_menu_items fast_menu_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_items
    ADD CONSTRAINT fast_menu_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3577 (class 2606 OID 33406)
-- Name: iiko_request_logs iiko_request_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.iiko_request_logs
    ADD CONSTRAINT iiko_request_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 3592 (class 2606 OID 33542)
-- Name: mailing_tasks mailing_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mailing_tasks
    ADD CONSTRAINT mailing_tasks_pkey PRIMARY KEY (id);


--
-- TOC entry 3488 (class 2606 OID 16632)
-- Name: menus menus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT menus_pkey PRIMARY KEY (menu_id);


--
-- TOC entry 3516 (class 2606 OID 16656)
-- Name: modifiers modifiers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modifiers
    ADD CONSTRAINT modifiers_pkey PRIMARY KEY (modifier_id);


--
-- TOC entry 3539 (class 2606 OID 16729)
-- Name: order_item_modifiers order_item_modifiers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item_modifiers
    ADD CONSTRAINT order_item_modifiers_pkey PRIMARY KEY (id);


--
-- TOC entry 3533 (class 2606 OID 16724)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3525 (class 2606 OID 16719)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- TOC entry 3417 (class 2606 OID 16831)
-- Name: organizations organizations_bot_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_bot_token_key UNIQUE (bot_token);


--
-- TOC entry 3419 (class 2606 OID 16406)
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (org_id);


--
-- TOC entry 3422 (class 2606 OID 16424)
-- Name: payment_types payment_types_organization_id_payment_id_a7d45cf2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_types
    ADD CONSTRAINT payment_types_organization_id_payment_id_a7d45cf2_uniq UNIQUE (organization_id, payment_id);


--
-- TOC entry 3424 (class 2606 OID 16411)
-- Name: payment_types payment_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_types
    ADD CONSTRAINT payment_types_pkey PRIMARY KEY (payment_id);


--
-- TOC entry 3492 (class 2606 OID 25176)
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3501 (class 2606 OID 25146)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3503 (class 2606 OID 25168)
-- Name: products products_product_id_menu_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_product_id_menu_uniq UNIQUE (product_id, menu_id);


--
-- TOC entry 3452 (class 2606 OID 16500)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3455 (class 2606 OID 16502)
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- TOC entry 3507 (class 2606 OID 16651)
-- Name: stop_list stop_list_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stop_list
    ADD CONSTRAINT stop_list_pkey PRIMARY KEY (id);


--
-- TOC entry 3511 (class 2606 OID 16848)
-- Name: stop_list stop_list_product_id_terminal_id_daf9b52f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stop_list
    ADD CONSTRAINT stop_list_product_id_terminal_id_daf9b52f_uniq UNIQUE (product_id, terminal_id);


--
-- TOC entry 3429 (class 2606 OID 16416)
-- Name: streets streets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.streets
    ADD CONSTRAINT streets_pkey PRIMARY KEY (street_id);


--
-- TOC entry 3414 (class 2606 OID 16397)
-- Name: terminals terminals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.terminals
    ADD CONSTRAINT terminals_pkey PRIMARY KEY (terminal_id);


--
-- TOC entry 3467 (class 2606 OID 16519)
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3470 (class 2606 OID 16548)
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 3458 (class 2606 OID 16509)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3461 (class 2606 OID 16513)
-- Name: users users_telegram_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_telegram_id_key UNIQUE (telegram_id);


--
-- TOC entry 3550 (class 2606 OID 16866)
-- Name: users_terminals users_terminals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_terminals
    ADD CONSTRAINT users_terminals_pkey PRIMARY KEY (id);


--
-- TOC entry 3554 (class 2606 OID 16868)
-- Name: users_terminals users_terminals_user_id_terminal_id_b21c0079_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_terminals
    ADD CONSTRAINT users_terminals_user_id_terminal_id_b21c0079_uniq UNIQUE (user_id, terminal_id);


--
-- TOC entry 3473 (class 2606 OID 16525)
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3476 (class 2606 OID 16562)
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 3464 (class 2606 OID 16511)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 3440 (class 1259 OID 16492)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3445 (class 1259 OID 16488)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3448 (class 1259 OID 16489)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3435 (class 1259 OID 16474)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3570 (class 1259 OID 16944)
-- Name: billing_pho_phone_8bd850_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX billing_pho_phone_8bd850_idx ON public.billing_phones USING btree (phone);


--
-- TOC entry 3571 (class 1259 OID 16943)
-- Name: billing_pho_user_id_7ce61b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX billing_pho_user_id_7ce61b_idx ON public.billing_phones USING btree (user_id);


--
-- TOC entry 3574 (class 1259 OID 16942)
-- Name: billing_phones_user_id_1eaed2ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX billing_phones_user_id_1eaed2ba ON public.billing_phones USING btree (user_id);


--
-- TOC entry 3583 (class 1259 OID 33573)
-- Name: bot_sync_to_bot_syn_151f68_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bot_sync_to_bot_syn_151f68_idx ON public.bot_sync_tokens USING btree (bot_sync_uuid);


--
-- TOC entry 3584 (class 1259 OID 33574)
-- Name: bot_sync_to_created_27ea4c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bot_sync_to_created_27ea4c_idx ON public.bot_sync_tokens USING btree (created_at);


--
-- TOC entry 3589 (class 1259 OID 33454)
-- Name: bot_sync_tokens_user_id_9d812337; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bot_sync_tokens_user_id_9d812337 ON public.bot_sync_tokens USING btree (user_id);


--
-- TOC entry 3540 (class 1259 OID 16828)
-- Name: cities_organization_id_a7ea96b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cities_organization_id_a7ea96b2 ON public.cities USING btree (organization_id);


--
-- TOC entry 3477 (class 1259 OID 16887)
-- Name: delivery_addresses_city_id_3b2118b3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delivery_addresses_city_id_3b2118b3 ON public.delivery_addresses USING btree (city_id);


--
-- TOC entry 3480 (class 1259 OID 16585)
-- Name: delivery_addresses_street_id_eb1cca2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delivery_addresses_street_id_eb1cca2c ON public.delivery_addresses USING btree (street_id);


--
-- TOC entry 3481 (class 1259 OID 16586)
-- Name: delivery_addresses_user_id_c5ba434f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delivery_addresses_user_id_c5ba434f ON public.delivery_addresses USING btree (user_id);


--
-- TOC entry 3580 (class 1259 OID 33427)
-- Name: discounts_organization_id_cdf772a4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX discounts_organization_id_cdf772a4 ON public.discounts USING btree (organization_id);


--
-- TOC entry 3482 (class 1259 OID 16606)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3485 (class 1259 OID 16607)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3545 (class 1259 OID 16859)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3548 (class 1259 OID 16858)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3555 (class 1259 OID 16907)
-- Name: fast_menu_g_is_acti_0649e2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_g_is_acti_0649e2_idx ON public.fast_menu_groups USING btree (is_active);


--
-- TOC entry 3556 (class 1259 OID 16908)
-- Name: fast_menu_g_order_66417c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_g_order_66417c_idx ON public.fast_menu_groups USING btree ("order");


--
-- TOC entry 3557 (class 1259 OID 16906)
-- Name: fast_menu_g_organiz_56a80c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_g_organiz_56a80c_idx ON public.fast_menu_groups USING btree (organization_id);


--
-- TOC entry 3558 (class 1259 OID 16919)
-- Name: fast_menu_groups_organization_id_52e65553; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_groups_organization_id_52e65553 ON public.fast_menu_groups USING btree (organization_id);


--
-- TOC entry 3561 (class 1259 OID 16909)
-- Name: fast_menu_i_group_i_55bbe3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_i_group_i_55bbe3_idx ON public.fast_menu_items USING btree (group_id);


--
-- TOC entry 3562 (class 1259 OID 16911)
-- Name: fast_menu_i_order_fd7e69_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_i_order_fd7e69_idx ON public.fast_menu_items USING btree ("order");


--
-- TOC entry 3563 (class 1259 OID 16910)
-- Name: fast_menu_i_product_4226e0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_i_product_4226e0_idx ON public.fast_menu_items USING btree (product_id);


--
-- TOC entry 3564 (class 1259 OID 16930)
-- Name: fast_menu_items_group_id_f8ea134b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_items_group_id_f8ea134b ON public.fast_menu_items USING btree (group_id);


--
-- TOC entry 3569 (class 1259 OID 16931)
-- Name: fast_menu_items_product_id_2a74c3b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fast_menu_items_product_id_2a74c3b6 ON public.fast_menu_items USING btree (product_id);


--
-- TOC entry 3575 (class 1259 OID 33412)
-- Name: iiko_request_logs_order_id_949325a1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX iiko_request_logs_order_id_949325a1 ON public.iiko_request_logs USING btree (order_id);


--
-- TOC entry 3590 (class 1259 OID 33548)
-- Name: mailing_tasks_organization_id_58230632; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mailing_tasks_organization_id_58230632 ON public.mailing_tasks USING btree (organization_id);


--
-- TOC entry 3486 (class 1259 OID 16669)
-- Name: menus_organization_id_e09bde4a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX menus_organization_id_e09bde4a ON public.menus USING btree (organization_id);


--
-- TOC entry 3514 (class 1259 OID 50089)
-- Name: modifiers_is_avail_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX modifiers_is_avail_idx ON public.modifiers USING btree (is_available);


--
-- TOC entry 3517 (class 1259 OID 16712)
-- Name: modifiers_product_f96e28_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX modifiers_product_f96e28_idx ON public.modifiers USING btree (product_id);


--
-- TOC entry 3518 (class 1259 OID 16711)
-- Name: modifiers_product_id_47a9c41e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX modifiers_product_id_47a9c41e ON public.modifiers USING btree (product_id);


--
-- TOC entry 3535 (class 1259 OID 16775)
-- Name: order_item__order_i_15de8c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item__order_i_15de8c_idx ON public.order_item_modifiers USING btree (order_item_id);


--
-- TOC entry 3536 (class 1259 OID 16782)
-- Name: order_item_modifiers_modifier_id_4d40bd5d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item_modifiers_modifier_id_4d40bd5d ON public.order_item_modifiers USING btree (modifier_id);


--
-- TOC entry 3537 (class 1259 OID 16783)
-- Name: order_item_modifiers_order_item_id_8c74638e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item_modifiers_order_item_id_8c74638e ON public.order_item_modifiers USING btree (order_item_id);


--
-- TOC entry 3530 (class 1259 OID 16774)
-- Name: order_items_order_i_26ad88_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_order_i_26ad88_idx ON public.order_items USING btree (order_id);


--
-- TOC entry 3531 (class 1259 OID 16780)
-- Name: order_items_order_id_412ad78b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_order_id_412ad78b ON public.order_items USING btree (order_id);


--
-- TOC entry 3534 (class 1259 OID 16781)
-- Name: order_items_product_id_dd557d5a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_product_id_dd557d5a ON public.order_items USING btree (product_id);


--
-- TOC entry 3519 (class 1259 OID 16773)
-- Name: orders_created_77e2b9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_created_77e2b9_idx ON public.orders USING btree (created_at);


--
-- TOC entry 3520 (class 1259 OID 16776)
-- Name: orders_delivery_address_id_e5955160; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_delivery_address_id_e5955160 ON public.orders USING btree (delivery_address_id);


--
-- TOC entry 3521 (class 1259 OID 16777)
-- Name: orders_org_id_2de76c46; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_org_id_2de76c46 ON public.orders USING btree (org_id);


--
-- TOC entry 3522 (class 1259 OID 16771)
-- Name: orders_org_id_4495b4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_org_id_4495b4_idx ON public.orders USING btree (org_id);


--
-- TOC entry 3523 (class 1259 OID 16778)
-- Name: orders_payment_type_id_ba38c7a9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_payment_type_id_ba38c7a9 ON public.orders USING btree (payment_type_id);


--
-- TOC entry 3526 (class 1259 OID 16772)
-- Name: orders_status_762191_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_status_762191_idx ON public.orders USING btree (status);


--
-- TOC entry 3527 (class 1259 OID 16789)
-- Name: orders_terminal_id_f2a3a529; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_terminal_id_f2a3a529 ON public.orders USING btree (terminal_id);


--
-- TOC entry 3528 (class 1259 OID 16770)
-- Name: orders_user_id_4e08b8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_user_id_4e08b8_idx ON public.orders USING btree (user_id);


--
-- TOC entry 3529 (class 1259 OID 16779)
-- Name: orders_user_id_7e2523fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_user_id_7e2523fb ON public.orders USING btree (user_id);


--
-- TOC entry 3415 (class 1259 OID 16832)
-- Name: organizations_bot_token_804c0dbf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organizations_bot_token_804c0dbf_like ON public.organizations USING btree (bot_token varchar_pattern_ops);


--
-- TOC entry 3420 (class 1259 OID 16430)
-- Name: payment_types_organization_id_94258e0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payment_types_organization_id_94258e0e ON public.payment_types USING btree (organization_id);


--
-- TOC entry 3489 (class 1259 OID 16675)
-- Name: product_categories_menu_id_054ffee6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_categories_menu_id_054ffee6 ON public.product_categories USING btree (menu_id);


--
-- TOC entry 3490 (class 1259 OID 16841)
-- Name: product_categories_parent_id_22d4dfe1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_categories_parent_id_22d4dfe1 ON public.product_categories USING btree (parent_id);


--
-- TOC entry 3493 (class 1259 OID 25177)
-- Name: product_categories_subgroup_menu_uniq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX product_categories_subgroup_menu_uniq ON public.product_categories USING btree (subgroup_id, menu_id);


--
-- TOC entry 3494 (class 1259 OID 16693)
-- Name: products_category_id_a7a3a156; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_id_a7a3a156 ON public.products USING btree (category_id);


--
-- TOC entry 3495 (class 1259 OID 16659)
-- Name: products_is_avai_39744e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_is_avai_39744e_idx ON public.products USING btree (is_available);


--
-- TOC entry 3496 (class 1259 OID 16657)
-- Name: products_menu_id_141187_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_menu_id_141187_idx ON public.products USING btree (menu_id);


--
-- TOC entry 3497 (class 1259 OID 16691)
-- Name: products_menu_id_92765861; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_menu_id_92765861 ON public.products USING btree (menu_id);


--
-- TOC entry 3498 (class 1259 OID 16658)
-- Name: products_organiz_d068f8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_organiz_d068f8_idx ON public.products USING btree (organization_id);


--
-- TOC entry 3499 (class 1259 OID 16692)
-- Name: products_organization_id_93bac7d3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_organization_id_93bac7d3 ON public.products USING btree (organization_id);


--
-- TOC entry 3453 (class 1259 OID 16533)
-- Name: roles_role_name_2c8c2fcd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_role_name_2c8c2fcd_like ON public.roles USING btree (role_name varchar_pattern_ops);


--
-- TOC entry 3504 (class 1259 OID 16661)
-- Name: stop_list_organiz_a9d081_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_organiz_a9d081_idx ON public.stop_list USING btree (organization_id);


--
-- TOC entry 3505 (class 1259 OID 16704)
-- Name: stop_list_organization_id_273fa59b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_organization_id_273fa59b ON public.stop_list USING btree (organization_id);


--
-- TOC entry 3508 (class 1259 OID 16660)
-- Name: stop_list_product_075571_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_product_075571_idx ON public.stop_list USING btree (product_id);


--
-- TOC entry 3509 (class 1259 OID 16705)
-- Name: stop_list_product_id_03b51ad2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_product_id_03b51ad2 ON public.stop_list USING btree (product_id);


--
-- TOC entry 3512 (class 1259 OID 16849)
-- Name: stop_list_termina_073d69_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_termina_073d69_idx ON public.stop_list USING btree (terminal_id);


--
-- TOC entry 3513 (class 1259 OID 16850)
-- Name: stop_list_terminal_id_6c32c48a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stop_list_terminal_id_6c32c48a ON public.stop_list USING btree (terminal_id);


--
-- TOC entry 3425 (class 1259 OID 16815)
-- Name: streets_city_id_eb4f6aee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX streets_city_id_eb4f6aee ON public.streets USING btree (city_id);


--
-- TOC entry 3426 (class 1259 OID 16437)
-- Name: streets_organiz_30b9b4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX streets_organiz_30b9b4_idx ON public.streets USING btree (organization_id);


--
-- TOC entry 3427 (class 1259 OID 16436)
-- Name: streets_organization_id_65b2a4f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX streets_organization_id_65b2a4f7 ON public.streets USING btree (organization_id);


--
-- TOC entry 3430 (class 1259 OID 16438)
-- Name: streets_street__39922a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX streets_street__39922a_idx ON public.streets USING btree (street_name);


--
-- TOC entry 3411 (class 1259 OID 16829)
-- Name: terminals_city_id_019d8aab; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX terminals_city_id_019d8aab ON public.terminals USING btree (city_id);


--
-- TOC entry 3412 (class 1259 OID 16797)
-- Name: terminals_organization_id_53848a5a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX terminals_organization_id_53848a5a ON public.terminals USING btree (organization_id);


--
-- TOC entry 3465 (class 1259 OID 16560)
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- TOC entry 3468 (class 1259 OID 16559)
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- TOC entry 3456 (class 1259 OID 16545)
-- Name: users_org_id_e531df03; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_org_id_e531df03 ON public.users USING btree (org_id);


--
-- TOC entry 3459 (class 1259 OID 16546)
-- Name: users_role_id_1900a745; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_role_id_1900a745 ON public.users USING btree (role_id);


--
-- TOC entry 3551 (class 1259 OID 16880)
-- Name: users_terminals_terminal_id_0987e014; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_terminals_terminal_id_0987e014 ON public.users_terminals USING btree (terminal_id);


--
-- TOC entry 3552 (class 1259 OID 16879)
-- Name: users_terminals_user_id_f42ea2e6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_terminals_user_id_f42ea2e6 ON public.users_terminals USING btree (user_id);


--
-- TOC entry 3471 (class 1259 OID 16574)
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- TOC entry 3474 (class 1259 OID 16573)
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- TOC entry 3462 (class 1259 OID 16544)
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- TOC entry 3599 (class 2606 OID 16483)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3600 (class 2606 OID 16478)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3598 (class 2606 OID 16469)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3637 (class 2606 OID 16937)
-- Name: billing_phones billing_phones_user_id_1eaed2ba_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_phones
    ADD CONSTRAINT billing_phones_user_id_1eaed2ba_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3640 (class 2606 OID 33449)
-- Name: bot_sync_tokens bot_sync_tokens_user_id_9d812337_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bot_sync_tokens
    ADD CONSTRAINT bot_sync_tokens_user_id_9d812337_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3631 (class 2606 OID 16823)
-- Name: cities cities_organization_id_a7ea96b2_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_organization_id_a7ea96b2_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3607 (class 2606 OID 16882)
-- Name: delivery_addresses delivery_addresses_city_id_3b2118b3_fk_cities_city_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_addresses
    ADD CONSTRAINT delivery_addresses_city_id_3b2118b3_fk_cities_city_id FOREIGN KEY (city_id) REFERENCES public.cities(city_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3608 (class 2606 OID 16575)
-- Name: delivery_addresses delivery_addresses_street_id_eb1cca2c_fk_streets_street_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_addresses
    ADD CONSTRAINT delivery_addresses_street_id_eb1cca2c_fk_streets_street_id FOREIGN KEY (street_id) REFERENCES public.streets(street_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3609 (class 2606 OID 16580)
-- Name: delivery_addresses delivery_addresses_user_id_c5ba434f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_addresses
    ADD CONSTRAINT delivery_addresses_user_id_c5ba434f_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3639 (class 2606 OID 33422)
-- Name: discounts discounts_organization_id_cdf772a4_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_organization_id_cdf772a4_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3610 (class 2606 OID 16596)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3611 (class 2606 OID 16601)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3634 (class 2606 OID 16914)
-- Name: fast_menu_groups fast_menu_groups_organization_id_52e65553_fk_organizat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_groups
    ADD CONSTRAINT fast_menu_groups_organization_id_52e65553_fk_organizat FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3635 (class 2606 OID 16920)
-- Name: fast_menu_items fast_menu_items_group_id_f8ea134b_fk_fast_menu_groups_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_items
    ADD CONSTRAINT fast_menu_items_group_id_f8ea134b_fk_fast_menu_groups_id FOREIGN KEY (group_id) REFERENCES public.fast_menu_groups(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3636 (class 2606 OID 25157)
-- Name: fast_menu_items fast_menu_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fast_menu_items
    ADD CONSTRAINT fast_menu_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 3638 (class 2606 OID 33407)
-- Name: iiko_request_logs iiko_request_logs_order_id_949325a1_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.iiko_request_logs
    ADD CONSTRAINT iiko_request_logs_order_id_949325a1_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders(order_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3641 (class 2606 OID 33543)
-- Name: mailing_tasks mailing_tasks_organization_id_58230632_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mailing_tasks
    ADD CONSTRAINT mailing_tasks_organization_id_58230632_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3612 (class 2606 OID 16664)
-- Name: menus menus_organization_id_e09bde4a_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT menus_organization_id_e09bde4a_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3621 (class 2606 OID 25152)
-- Name: modifiers modifiers_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modifiers
    ADD CONSTRAINT modifiers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 3629 (class 2606 OID 16760)
-- Name: order_item_modifiers order_item_modifiers_modifier_id_4d40bd5d_fk_modifiers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item_modifiers
    ADD CONSTRAINT order_item_modifiers_modifier_id_4d40bd5d_fk_modifiers FOREIGN KEY (modifier_id) REFERENCES public.modifiers(modifier_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3630 (class 2606 OID 16765)
-- Name: order_item_modifiers order_item_modifiers_order_item_id_8c74638e_fk_order_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item_modifiers
    ADD CONSTRAINT order_item_modifiers_order_item_id_8c74638e_fk_order_items_id FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3627 (class 2606 OID 16750)
-- Name: order_items order_items_order_id_412ad78b_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_412ad78b_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders(order_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3628 (class 2606 OID 25162)
-- Name: order_items order_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT;


--
-- TOC entry 3622 (class 2606 OID 16730)
-- Name: orders orders_delivery_address_id_e5955160_fk_delivery_addresses_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_delivery_address_id_e5955160_fk_delivery_addresses_id FOREIGN KEY (delivery_address_id) REFERENCES public.delivery_addresses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3623 (class 2606 OID 16735)
-- Name: orders orders_org_id_2de76c46_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_org_id_2de76c46_fk_organizations_org_id FOREIGN KEY (org_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3624 (class 2606 OID 16740)
-- Name: orders orders_payment_type_id_ba38c7a9_fk_payment_types_payment_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_payment_type_id_ba38c7a9_fk_payment_types_payment_id FOREIGN KEY (payment_type_id) REFERENCES public.payment_types(payment_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3625 (class 2606 OID 16784)
-- Name: orders orders_terminal_id_f2a3a529_fk_terminals_terminal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_terminal_id_f2a3a529_fk_terminals_terminal_id FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3626 (class 2606 OID 16745)
-- Name: orders orders_user_id_7e2523fb_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_7e2523fb_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3595 (class 2606 OID 16425)
-- Name: payment_types payment_types_organization_id_94258e0e_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_types
    ADD CONSTRAINT payment_types_organization_id_94258e0e_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3613 (class 2606 OID 16670)
-- Name: product_categories product_categories_menu_id_054ffee6_fk_menus_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_menu_id_054ffee6_fk_menus_menu_id FOREIGN KEY (menu_id) REFERENCES public.menus(menu_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3614 (class 2606 OID 25183)
-- Name: product_categories product_categories_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.product_categories(id) ON DELETE SET NULL;


--
-- TOC entry 3615 (class 2606 OID 25178)
-- Name: products products_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id) ON DELETE SET NULL;


--
-- TOC entry 3616 (class 2606 OID 16676)
-- Name: products products_menu_id_92765861_fk_menus_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_menu_id_92765861_fk_menus_menu_id FOREIGN KEY (menu_id) REFERENCES public.menus(menu_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3617 (class 2606 OID 16681)
-- Name: products products_organization_id_93bac7d3_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_organization_id_93bac7d3_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3618 (class 2606 OID 16694)
-- Name: stop_list stop_list_organization_id_273fa59b_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stop_list
    ADD CONSTRAINT stop_list_organization_id_273fa59b_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3619 (class 2606 OID 25147)
-- Name: stop_list stop_list_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stop_list
    ADD CONSTRAINT stop_list_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 3620 (class 2606 OID 16842)
-- Name: stop_list stop_list_terminal_id_6c32c48a_fk_terminals_terminal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stop_list
    ADD CONSTRAINT stop_list_terminal_id_6c32c48a_fk_terminals_terminal_id FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3596 (class 2606 OID 16816)
-- Name: streets streets_city_id_eb4f6aee_fk_cities_city_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.streets
    ADD CONSTRAINT streets_city_id_eb4f6aee_fk_cities_city_id FOREIGN KEY (city_id) REFERENCES public.cities(city_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3597 (class 2606 OID 16431)
-- Name: streets streets_organization_id_65b2a4f7_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.streets
    ADD CONSTRAINT streets_organization_id_65b2a4f7_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3593 (class 2606 OID 16803)
-- Name: terminals terminals_city_id_019d8aab_fk_cities_city_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.terminals
    ADD CONSTRAINT terminals_city_id_019d8aab_fk_cities_city_id FOREIGN KEY (city_id) REFERENCES public.cities(city_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3594 (class 2606 OID 16792)
-- Name: terminals terminals_organization_id_53848a5a_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.terminals
    ADD CONSTRAINT terminals_organization_id_53848a5a_fk_organizations_org_id FOREIGN KEY (organization_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3603 (class 2606 OID 16554)
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3604 (class 2606 OID 16549)
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3601 (class 2606 OID 16534)
-- Name: users users_org_id_e531df03_fk_organizations_org_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_org_id_e531df03_fk_organizations_org_id FOREIGN KEY (org_id) REFERENCES public.organizations(org_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3602 (class 2606 OID 16539)
-- Name: users users_role_id_1900a745_fk_roles_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_role_id_1900a745_fk_roles_id FOREIGN KEY (role_id) REFERENCES public.roles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3632 (class 2606 OID 16874)
-- Name: users_terminals users_terminals_terminal_id_0987e014_fk_terminals_terminal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_terminals
    ADD CONSTRAINT users_terminals_terminal_id_0987e014_fk_terminals_terminal_id FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3633 (class 2606 OID 16869)
-- Name: users_terminals users_terminals_user_id_f42ea2e6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_terminals
    ADD CONSTRAINT users_terminals_user_id_f42ea2e6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3605 (class 2606 OID 16568)
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3606 (class 2606 OID 16563)
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-04-23 10:20:40 +05

--
-- PostgreSQL database dump complete
--

\unrestrict uV3cNUiEEwguLkF6r3veQAwYGE4YG17j9hJf4XNre6xTIBl0Na6mudR242XokLv

