# Generated by Django 4.2.11 on 2026-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_bot_subscribed_user_language_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор'), ('master', 'Мастер'), ('client', 'Клиент')], default='client', max_length=20),
        ),
    ]
