# Generated by Django 4.2.11 on 2026-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_sync_uuid',
            field=models.UUIDField(blank=True, help_text='Used to pair bot interactions with this user', null=True, unique=True),
        ),
    ]
