# Generated by Django 4.2.11 on 2026-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bot_sync_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор'), ('owner', 'Владелец'), ('master', 'Мастер'), ('client', 'Клиент')], default='client', max_length=20),
        ),
    ]
