server {
    listen 80;
    client_max_body_size 20M;

    # TMA — отдельный SPA под /tma/
    location /tma/ {
        alias /usr/share/nginx/html/tma/;
        try_files $uri $uri/ /tma/index.html;
    }

    # API — проксируем на Django
    location /api/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django Admin
    location /administrator/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Static files for Django Admin
    location /static/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Media files (uploaded photos, etc.)
    location /media/ {
        alias /app/media/;
    }

    # Admin Panel — основной SPA
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
