# Generated by Django 4.2.11 on 2026-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='20:00')),
                ('lunch_start', models.TimeField(default='13:00')),
                ('lunch_end', models.TimeField(default='14:00')),
                ('bot_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
