# Generated by Django 4.2.11 on 2026-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='design_color',
            field=models.CharField(default='#c9a84c', help_text='Hex color code for the TMA theme', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='greeting_text',
            field=models.CharField(default='Добро пожаловать!', help_text='Greeting text in the TMA header', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link to Instagram profile', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo for TMA header', null=True, upload_to='organizations/logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20, null=True),
        ),
    ]
