# Generated by Django 4.2.11 on 2026-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_design_color_organization_greeting_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for maps geocoding', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for maps geocoding', null=True),
        ),
    ]
