# Generated by Django 4.2.11 on 2026-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_latitude_organization_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bot_username',
            field=models.CharField(blank=True, help_text='Username of the bot (without @)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tma_name',
            field=models.CharField(blank=True, help_text='Short name of the Mini App in BotFather', max_length=100, null=True),
        ),
    ]
