# Generated by Django 4.2.11 on 2026-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_bot_username_organization_tma_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_reminders_enabled',
            field=models.BooleanField(default=False, help_text='Включить автоматическую рассылку напоминаний'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reminder_hours_before',
            field=models.PositiveIntegerField(default=1, help_text='За сколько часов до записи отправлять напоминание'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reminder_template_kz',
            field=models.TextField(default='Сәлем, {User_name}! {Organization_name} салонындағы сағат {Start_time}-дегі жазбаңызды еске саламыз.\n\nҚызмет: {Service_name}\nШебер: {Master_name}\n\nКелесіз бе?', help_text='Шаблон на казахском. Плейсхолдеры: {Organization_name}, {User_name}, {Service_name}, {Master_name}, {Start_time}'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reminder_template_ru',
            field=models.TextField(default='Привет, {User_name}! Напоминаем о вашей записи в {Organization_name} в {Start_time}.\n\nУслуга: {Service_name}\nМастер: {Master_name}\n\nВы придете?', help_text='Шаблон на русском. Плейсхолдеры: {Organization_name}, {User_name}, {Service_name}, {Master_name}, {Start_time}'),
        ),
    ]
