# Generated by Django 4.2.11 on 2026-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_is_reminders_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='Базовая длительность слота в минутах (шаг записи)'),
        ),
    ]
