# Generated by Django 4.2.11 on 2026-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_lunch_break',
            field=models.BooleanField(default=True, help_text='Включить обеденный перерыв'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lunch_end',
            field=models.TimeField(blank=True, default='14:00', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lunch_start',
            field=models.TimeField(blank=True, default='13:00', null=True),
        ),
    ]
