# Generated by Django 4.2.11 on 2026-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_has_lunch_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_online_booking_enabled',
            field=models.BooleanField(default=True, help_text='Включить модуль онлайн-записи для клиентов'),
        ),
    ]
