# Generated by Django 4.2.11 on 2026-04-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_is_online_booking_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_online_booking_enabled',
        ),
    ]
