# Generated by Django 4.2.11 on 2026-05-10 13:03

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_organization_is_online_booking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_prepayment_enabled',
            field=models.BooleanField(default=False, help_text='Включить предоплату через Kaspi QR'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kaspi_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Kaspi ApiKey (хранится в зашифрованном виде)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='kaspi_device_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Kaspi DeviceToken (хранится в зашифрованном виде)', null=True),
        ),
    ]
