# Generated by Django 4.2.11 on 2026-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_organization_is_prepayment_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bin_iin',
            field=models.CharField(blank=True, help_text='БИН/ИИН продавца для проверки квитанции', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='kaspi_payment_link',
            field=models.URLField(blank=True, help_text='Статическая ссылка на Kaspi QR', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(choices=[('AUTOMATIC', 'Kaspi API (Автоматический)'), ('SEMI_AUTOMATIC', 'Kaspi QR Link (Полуавтоматический)'), ('MANUAL', 'Выставление счета (Ручной)')], default='MANUAL', help_text='Способ оплаты предоплаты', max_length=20),
        ),
    ]
