# Generated by Django 4.2.11 on 2026-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_bin_iin_organization_kaspi_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tma_link',
            field=models.URLField(blank=True, help_text='Базовая ссылка на Telegram Mini App (например, https://t.me/jazoo_bot/app)', null=True),
        ),
    ]
