# Generated by Django 4.2.11 on 2026-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_tma_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tma_link',
            field=models.URLField(blank=True, help_text='Базовая ссылка на Mini App (например, https://t.me/jazoo_bot/app)', max_length=500, null=True),
        ),
    ]
