# Generated by Django 4.2.11 on 2026-05-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0011_organization_bin_iin_organization_kaspi_payment_link_and_more'),
        ('appointments', '0012_appointment_receipt_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_receipts', to='appointments.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_receipts', to='organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'receipt_number')},
            },
        ),
    ]
